# Generated by Django 6.0.4 on 2026-06-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gramsangam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mandiprice',
            name='crop_name',
            field=models.CharField(default='Wheat', max_length=100),
        ),
        migrations.AlterField(
            model_name='mandiprice',
            name='mandi_name',
            field=models.CharField(default='Harsud', max_length=100),
        ),
        migrations.AlterField(
            model_name='mandiprice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
